#ifndef PLAN_STATE_SYSTEM_H
#define PLAN_STATE_SYSTEM_H

#include "plan_include.h"
#include <stddef.h>

typedef enum
{
  EVENT_INITIALIZATION_SUCCESS,
  EVENT_INITIALIZATION_FAIL,
  EVENT_EXTERNAL_MEMORY_DETECTED,
  EVENT_EXTERNAL_MEMORY_DISCONNECTED,
  EVENT_MEMORY_INITIALIZATION_SUCCESS,
  EVENT_MANIFEST_READ_SUCCESS,
  EVENT_MANIFEST_READ_FAIL,
  EVENT_FSM_BUILD_SUCCESS,
  EVENT_FSM_BUILD_FAIL,
  EVENT_USER_FSM_INITIALIZE,
  EVENT_FSM_INITIALIZED,
  EVENT_FLEXSEA_ERROR = 0xFF,
} event;

typedef enum
{
  STATE_ERROR,
  STATE_INITIALIZING,
  STATE_INITIALIZING_MEMORY,
  STATE_WAITING_FOR_MANIFEST,
  STATE_READING_MANIFEST,
  STATE_INCORRECT_MANIFEST,
  STATE_BUILDING_FSM,
  STATE_WAIT_FOR_USER,
  STATE_INITIALIZING_FSM,
  STATE_ACTIVE_CONTROL,
} state;

typedef struct 
{
  state source;
  event event;
  state destination;
} transition;

#define ENTRY_STATE     STATE_INITIALIZING

void change_sys_state(state* curstate_p, event curevent);

#endif //PLAN_STATE_SYSTEM_H
